### ISSUE TITLE
Tab display problem

### ISSUE THREAD

**Issue by samtrion** [dotnet/EntityFramework.Docs.de-de#22] opened 2020-11-27 11:08 UTC
On the page listed here, the tabs are shown duplicated several times.

![image](https://user-images.githubusercontent.com/3283596/100442837-0071db00-30a9-11eb-9f24-917ff35b953a.png)
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a4381838-81bb-52c6-d921-f8b9ae8163d2
* Version Independent ID: 892a8dd8-7a63-ce0b-de20-27e92b88f971
* Content: [Entitäts Eigenschaften-EF Core](https://docs.microsoft.com/de-de/ef/core/modeling/entity-properties?tabs=data-annotations)
* Content Source: [entity-framework/core/modeling/entity-properties.md](https://github.com/dotnet/EntityFramework.Docs.de-de/blob/live/entity-framework/core/modeling/entity-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2020-11-27 17:06
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2900

**Comment by JasonCard** [comment] 2020-12-01 20:14
Thank you for reporting this issue and I'm following up.

**Comment by JasonCard** [comment] 2021-02-10 01:43
This issue is now fixed :)

**Closed by JasonCard** 2021-02-10 01:43 UTC
